# HTTP 服务端口
server.port=8070

# ==================== 日志配置 ====================
# 日志文件输出目录
logging.file.path=logs
# 根日志级别
logging.level.root=INFO

# ==================== Nacos ====================
# Nacos 配置中心地址
spring.cloud.nacos.config.server-addr=127.0.0.1:8848
# Nacos 服务注册与发现地址
spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848

